
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CV` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model CV
 * 
 */
export type CVModel = runtime.Types.Result.DefaultSelection<Prisma.$CVPayload>

export type AggregateCV = {
  _count: CVCountAggregateOutputType | null
  _min: CVMinAggregateOutputType | null
  _max: CVMaxAggregateOutputType | null
}

export type CVMinAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
}

export type CVMaxAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
}

export type CVCountAggregateOutputType = {
  id: number
  name: number
  email: number
  _all: number
}


export type CVMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
}

export type CVMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
}

export type CVCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  _all?: true
}

export type CVAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CV to aggregate.
   */
  where?: Prisma.CVWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CVS to fetch.
   */
  orderBy?: Prisma.CVOrderByWithRelationInput | Prisma.CVOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CVWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CVS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CVS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CVS
  **/
  _count?: true | CVCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CVMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CVMaxAggregateInputType
}

export type GetCVAggregateType<T extends CVAggregateArgs> = {
      [P in keyof T & keyof AggregateCV]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCV[P]>
    : Prisma.GetScalarType<T[P], AggregateCV[P]>
}




export type CVGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CVWhereInput
  orderBy?: Prisma.CVOrderByWithAggregationInput | Prisma.CVOrderByWithAggregationInput[]
  by: Prisma.CVScalarFieldEnum[] | Prisma.CVScalarFieldEnum
  having?: Prisma.CVScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CVCountAggregateInputType | true
  _min?: CVMinAggregateInputType
  _max?: CVMaxAggregateInputType
}

export type CVGroupByOutputType = {
  id: string
  name: string
  email: string
  _count: CVCountAggregateOutputType | null
  _min: CVMinAggregateOutputType | null
  _max: CVMaxAggregateOutputType | null
}

export type GetCVGroupByPayload<T extends CVGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CVGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CVGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CVGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CVGroupByOutputType[P]>
      }
    >
  >



export type CVWhereInput = {
  AND?: Prisma.CVWhereInput | Prisma.CVWhereInput[]
  OR?: Prisma.CVWhereInput[]
  NOT?: Prisma.CVWhereInput | Prisma.CVWhereInput[]
  id?: Prisma.StringFilter<"CV"> | string
  name?: Prisma.StringFilter<"CV"> | string
  email?: Prisma.StringFilter<"CV"> | string
  attribute_values?: Prisma.AttributeValueListRelationFilter
}

export type CVOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  attribute_values?: Prisma.AttributeValueOrderByRelationAggregateInput
}

export type CVWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CVWhereInput | Prisma.CVWhereInput[]
  OR?: Prisma.CVWhereInput[]
  NOT?: Prisma.CVWhereInput | Prisma.CVWhereInput[]
  name?: Prisma.StringFilter<"CV"> | string
  email?: Prisma.StringFilter<"CV"> | string
  attribute_values?: Prisma.AttributeValueListRelationFilter
}, "id">

export type CVOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  _count?: Prisma.CVCountOrderByAggregateInput
  _max?: Prisma.CVMaxOrderByAggregateInput
  _min?: Prisma.CVMinOrderByAggregateInput
}

export type CVScalarWhereWithAggregatesInput = {
  AND?: Prisma.CVScalarWhereWithAggregatesInput | Prisma.CVScalarWhereWithAggregatesInput[]
  OR?: Prisma.CVScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CVScalarWhereWithAggregatesInput | Prisma.CVScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CV"> | string
  name?: Prisma.StringWithAggregatesFilter<"CV"> | string
  email?: Prisma.StringWithAggregatesFilter<"CV"> | string
}

export type CVCreateInput = {
  id?: string
  name: string
  email: string
  attribute_values?: Prisma.AttributeValueCreateNestedManyWithoutCvInput
}

export type CVUncheckedCreateInput = {
  id?: string
  name: string
  email: string
  attribute_values?: Prisma.AttributeValueUncheckedCreateNestedManyWithoutCvInput
}

export type CVUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  attribute_values?: Prisma.AttributeValueUpdateManyWithoutCvNestedInput
}

export type CVUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  attribute_values?: Prisma.AttributeValueUncheckedUpdateManyWithoutCvNestedInput
}

export type CVCreateManyInput = {
  id?: string
  name: string
  email: string
}

export type CVUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CVUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CVScalarRelationFilter = {
  is?: Prisma.CVWhereInput
  isNot?: Prisma.CVWhereInput
}

export type CVCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
}

export type CVMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
}

export type CVMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
}

export type CVCreateNestedOneWithoutAttribute_valuesInput = {
  create?: Prisma.XOR<Prisma.CVCreateWithoutAttribute_valuesInput, Prisma.CVUncheckedCreateWithoutAttribute_valuesInput>
  connectOrCreate?: Prisma.CVCreateOrConnectWithoutAttribute_valuesInput
  connect?: Prisma.CVWhereUniqueInput
}

export type CVUpdateOneRequiredWithoutAttribute_valuesNestedInput = {
  create?: Prisma.XOR<Prisma.CVCreateWithoutAttribute_valuesInput, Prisma.CVUncheckedCreateWithoutAttribute_valuesInput>
  connectOrCreate?: Prisma.CVCreateOrConnectWithoutAttribute_valuesInput
  upsert?: Prisma.CVUpsertWithoutAttribute_valuesInput
  connect?: Prisma.CVWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CVUpdateToOneWithWhereWithoutAttribute_valuesInput, Prisma.CVUpdateWithoutAttribute_valuesInput>, Prisma.CVUncheckedUpdateWithoutAttribute_valuesInput>
}

export type CVCreateWithoutAttribute_valuesInput = {
  id?: string
  name: string
  email: string
}

export type CVUncheckedCreateWithoutAttribute_valuesInput = {
  id?: string
  name: string
  email: string
}

export type CVCreateOrConnectWithoutAttribute_valuesInput = {
  where: Prisma.CVWhereUniqueInput
  create: Prisma.XOR<Prisma.CVCreateWithoutAttribute_valuesInput, Prisma.CVUncheckedCreateWithoutAttribute_valuesInput>
}

export type CVUpsertWithoutAttribute_valuesInput = {
  update: Prisma.XOR<Prisma.CVUpdateWithoutAttribute_valuesInput, Prisma.CVUncheckedUpdateWithoutAttribute_valuesInput>
  create: Prisma.XOR<Prisma.CVCreateWithoutAttribute_valuesInput, Prisma.CVUncheckedCreateWithoutAttribute_valuesInput>
  where?: Prisma.CVWhereInput
}

export type CVUpdateToOneWithWhereWithoutAttribute_valuesInput = {
  where?: Prisma.CVWhereInput
  data: Prisma.XOR<Prisma.CVUpdateWithoutAttribute_valuesInput, Prisma.CVUncheckedUpdateWithoutAttribute_valuesInput>
}

export type CVUpdateWithoutAttribute_valuesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CVUncheckedUpdateWithoutAttribute_valuesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type CVCountOutputType
 */

export type CVCountOutputType = {
  attribute_values: number
}

export type CVCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  attribute_values?: boolean | CVCountOutputTypeCountAttribute_valuesArgs
}

/**
 * CVCountOutputType without action
 */
export type CVCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CVCountOutputType
   */
  select?: Prisma.CVCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CVCountOutputType without action
 */
export type CVCountOutputTypeCountAttribute_valuesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AttributeValueWhereInput
}


export type CVSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  attribute_values?: boolean | Prisma.CV$attribute_valuesArgs<ExtArgs>
  _count?: boolean | Prisma.CVCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cV"]>

export type CVSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
}, ExtArgs["result"]["cV"]>

export type CVSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
}, ExtArgs["result"]["cV"]>

export type CVSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
}

export type CVOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email", ExtArgs["result"]["cV"]>
export type CVInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  attribute_values?: boolean | Prisma.CV$attribute_valuesArgs<ExtArgs>
  _count?: boolean | Prisma.CVCountOutputTypeDefaultArgs<ExtArgs>
}
export type CVIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type CVIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $CVPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CV"
  objects: {
    attribute_values: Prisma.$AttributeValuePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    email: string
  }, ExtArgs["result"]["cV"]>
  composites: {}
}

export type CVGetPayload<S extends boolean | null | undefined | CVDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CVPayload, S>

export type CVCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CVFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CVCountAggregateInputType | true
  }

export interface CVDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CV'], meta: { name: 'CV' } }
  /**
   * Find zero or one CV that matches the filter.
   * @param {CVFindUniqueArgs} args - Arguments to find a CV
   * @example
   * // Get one CV
   * const cV = await prisma.cV.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CVFindUniqueArgs>(args: Prisma.SelectSubset<T, CVFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CVClient<runtime.Types.Result.GetResult<Prisma.$CVPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CV that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CVFindUniqueOrThrowArgs} args - Arguments to find a CV
   * @example
   * // Get one CV
   * const cV = await prisma.cV.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CVFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CVFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CVClient<runtime.Types.Result.GetResult<Prisma.$CVPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CV that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CVFindFirstArgs} args - Arguments to find a CV
   * @example
   * // Get one CV
   * const cV = await prisma.cV.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CVFindFirstArgs>(args?: Prisma.SelectSubset<T, CVFindFirstArgs<ExtArgs>>): Prisma.Prisma__CVClient<runtime.Types.Result.GetResult<Prisma.$CVPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CV that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CVFindFirstOrThrowArgs} args - Arguments to find a CV
   * @example
   * // Get one CV
   * const cV = await prisma.cV.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CVFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CVFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CVClient<runtime.Types.Result.GetResult<Prisma.$CVPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CVS that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CVFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CVS
   * const cVS = await prisma.cV.findMany()
   * 
   * // Get first 10 CVS
   * const cVS = await prisma.cV.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const cVWithIdOnly = await prisma.cV.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CVFindManyArgs>(args?: Prisma.SelectSubset<T, CVFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CVPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CV.
   * @param {CVCreateArgs} args - Arguments to create a CV.
   * @example
   * // Create one CV
   * const CV = await prisma.cV.create({
   *   data: {
   *     // ... data to create a CV
   *   }
   * })
   * 
   */
  create<T extends CVCreateArgs>(args: Prisma.SelectSubset<T, CVCreateArgs<ExtArgs>>): Prisma.Prisma__CVClient<runtime.Types.Result.GetResult<Prisma.$CVPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CVS.
   * @param {CVCreateManyArgs} args - Arguments to create many CVS.
   * @example
   * // Create many CVS
   * const cV = await prisma.cV.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CVCreateManyArgs>(args?: Prisma.SelectSubset<T, CVCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CVS and returns the data saved in the database.
   * @param {CVCreateManyAndReturnArgs} args - Arguments to create many CVS.
   * @example
   * // Create many CVS
   * const cV = await prisma.cV.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CVS and only return the `id`
   * const cVWithIdOnly = await prisma.cV.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CVCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CVCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CVPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CV.
   * @param {CVDeleteArgs} args - Arguments to delete one CV.
   * @example
   * // Delete one CV
   * const CV = await prisma.cV.delete({
   *   where: {
   *     // ... filter to delete one CV
   *   }
   * })
   * 
   */
  delete<T extends CVDeleteArgs>(args: Prisma.SelectSubset<T, CVDeleteArgs<ExtArgs>>): Prisma.Prisma__CVClient<runtime.Types.Result.GetResult<Prisma.$CVPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CV.
   * @param {CVUpdateArgs} args - Arguments to update one CV.
   * @example
   * // Update one CV
   * const cV = await prisma.cV.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CVUpdateArgs>(args: Prisma.SelectSubset<T, CVUpdateArgs<ExtArgs>>): Prisma.Prisma__CVClient<runtime.Types.Result.GetResult<Prisma.$CVPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CVS.
   * @param {CVDeleteManyArgs} args - Arguments to filter CVS to delete.
   * @example
   * // Delete a few CVS
   * const { count } = await prisma.cV.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CVDeleteManyArgs>(args?: Prisma.SelectSubset<T, CVDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CVS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CVUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CVS
   * const cV = await prisma.cV.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CVUpdateManyArgs>(args: Prisma.SelectSubset<T, CVUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CVS and returns the data updated in the database.
   * @param {CVUpdateManyAndReturnArgs} args - Arguments to update many CVS.
   * @example
   * // Update many CVS
   * const cV = await prisma.cV.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CVS and only return the `id`
   * const cVWithIdOnly = await prisma.cV.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CVUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CVUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CVPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CV.
   * @param {CVUpsertArgs} args - Arguments to update or create a CV.
   * @example
   * // Update or create a CV
   * const cV = await prisma.cV.upsert({
   *   create: {
   *     // ... data to create a CV
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CV we want to update
   *   }
   * })
   */
  upsert<T extends CVUpsertArgs>(args: Prisma.SelectSubset<T, CVUpsertArgs<ExtArgs>>): Prisma.Prisma__CVClient<runtime.Types.Result.GetResult<Prisma.$CVPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CVS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CVCountArgs} args - Arguments to filter CVS to count.
   * @example
   * // Count the number of CVS
   * const count = await prisma.cV.count({
   *   where: {
   *     // ... the filter for the CVS we want to count
   *   }
   * })
  **/
  count<T extends CVCountArgs>(
    args?: Prisma.Subset<T, CVCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CVCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CV.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CVAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CVAggregateArgs>(args: Prisma.Subset<T, CVAggregateArgs>): Prisma.PrismaPromise<GetCVAggregateType<T>>

  /**
   * Group by CV.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CVGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CVGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CVGroupByArgs['orderBy'] }
      : { orderBy?: CVGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CVGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCVGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CV model
 */
readonly fields: CVFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CV.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CVClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  attribute_values<T extends Prisma.CV$attribute_valuesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CV$attribute_valuesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttributeValuePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CV model
 */
export interface CVFieldRefs {
  readonly id: Prisma.FieldRef<"CV", 'String'>
  readonly name: Prisma.FieldRef<"CV", 'String'>
  readonly email: Prisma.FieldRef<"CV", 'String'>
}
    

// Custom InputTypes
/**
 * CV findUnique
 */
export type CVFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CV
   */
  select?: Prisma.CVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CV
   */
  omit?: Prisma.CVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CVInclude<ExtArgs> | null
  /**
   * Filter, which CV to fetch.
   */
  where: Prisma.CVWhereUniqueInput
}

/**
 * CV findUniqueOrThrow
 */
export type CVFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CV
   */
  select?: Prisma.CVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CV
   */
  omit?: Prisma.CVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CVInclude<ExtArgs> | null
  /**
   * Filter, which CV to fetch.
   */
  where: Prisma.CVWhereUniqueInput
}

/**
 * CV findFirst
 */
export type CVFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CV
   */
  select?: Prisma.CVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CV
   */
  omit?: Prisma.CVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CVInclude<ExtArgs> | null
  /**
   * Filter, which CV to fetch.
   */
  where?: Prisma.CVWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CVS to fetch.
   */
  orderBy?: Prisma.CVOrderByWithRelationInput | Prisma.CVOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CVS.
   */
  cursor?: Prisma.CVWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CVS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CVS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CVS.
   */
  distinct?: Prisma.CVScalarFieldEnum | Prisma.CVScalarFieldEnum[]
}

/**
 * CV findFirstOrThrow
 */
export type CVFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CV
   */
  select?: Prisma.CVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CV
   */
  omit?: Prisma.CVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CVInclude<ExtArgs> | null
  /**
   * Filter, which CV to fetch.
   */
  where?: Prisma.CVWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CVS to fetch.
   */
  orderBy?: Prisma.CVOrderByWithRelationInput | Prisma.CVOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CVS.
   */
  cursor?: Prisma.CVWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CVS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CVS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CVS.
   */
  distinct?: Prisma.CVScalarFieldEnum | Prisma.CVScalarFieldEnum[]
}

/**
 * CV findMany
 */
export type CVFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CV
   */
  select?: Prisma.CVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CV
   */
  omit?: Prisma.CVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CVInclude<ExtArgs> | null
  /**
   * Filter, which CVS to fetch.
   */
  where?: Prisma.CVWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CVS to fetch.
   */
  orderBy?: Prisma.CVOrderByWithRelationInput | Prisma.CVOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CVS.
   */
  cursor?: Prisma.CVWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CVS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CVS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CVS.
   */
  distinct?: Prisma.CVScalarFieldEnum | Prisma.CVScalarFieldEnum[]
}

/**
 * CV create
 */
export type CVCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CV
   */
  select?: Prisma.CVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CV
   */
  omit?: Prisma.CVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CVInclude<ExtArgs> | null
  /**
   * The data needed to create a CV.
   */
  data: Prisma.XOR<Prisma.CVCreateInput, Prisma.CVUncheckedCreateInput>
}

/**
 * CV createMany
 */
export type CVCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CVS.
   */
  data: Prisma.CVCreateManyInput | Prisma.CVCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CV createManyAndReturn
 */
export type CVCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CV
   */
  select?: Prisma.CVSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CV
   */
  omit?: Prisma.CVOmit<ExtArgs> | null
  /**
   * The data used to create many CVS.
   */
  data: Prisma.CVCreateManyInput | Prisma.CVCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CV update
 */
export type CVUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CV
   */
  select?: Prisma.CVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CV
   */
  omit?: Prisma.CVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CVInclude<ExtArgs> | null
  /**
   * The data needed to update a CV.
   */
  data: Prisma.XOR<Prisma.CVUpdateInput, Prisma.CVUncheckedUpdateInput>
  /**
   * Choose, which CV to update.
   */
  where: Prisma.CVWhereUniqueInput
}

/**
 * CV updateMany
 */
export type CVUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CVS.
   */
  data: Prisma.XOR<Prisma.CVUpdateManyMutationInput, Prisma.CVUncheckedUpdateManyInput>
  /**
   * Filter which CVS to update
   */
  where?: Prisma.CVWhereInput
  /**
   * Limit how many CVS to update.
   */
  limit?: number
}

/**
 * CV updateManyAndReturn
 */
export type CVUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CV
   */
  select?: Prisma.CVSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CV
   */
  omit?: Prisma.CVOmit<ExtArgs> | null
  /**
   * The data used to update CVS.
   */
  data: Prisma.XOR<Prisma.CVUpdateManyMutationInput, Prisma.CVUncheckedUpdateManyInput>
  /**
   * Filter which CVS to update
   */
  where?: Prisma.CVWhereInput
  /**
   * Limit how many CVS to update.
   */
  limit?: number
}

/**
 * CV upsert
 */
export type CVUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CV
   */
  select?: Prisma.CVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CV
   */
  omit?: Prisma.CVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CVInclude<ExtArgs> | null
  /**
   * The filter to search for the CV to update in case it exists.
   */
  where: Prisma.CVWhereUniqueInput
  /**
   * In case the CV found by the `where` argument doesn't exist, create a new CV with this data.
   */
  create: Prisma.XOR<Prisma.CVCreateInput, Prisma.CVUncheckedCreateInput>
  /**
   * In case the CV was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CVUpdateInput, Prisma.CVUncheckedUpdateInput>
}

/**
 * CV delete
 */
export type CVDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CV
   */
  select?: Prisma.CVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CV
   */
  omit?: Prisma.CVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CVInclude<ExtArgs> | null
  /**
   * Filter which CV to delete.
   */
  where: Prisma.CVWhereUniqueInput
}

/**
 * CV deleteMany
 */
export type CVDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CVS to delete
   */
  where?: Prisma.CVWhereInput
  /**
   * Limit how many CVS to delete.
   */
  limit?: number
}

/**
 * CV.attribute_values
 */
export type CV$attribute_valuesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttributeValue
   */
  select?: Prisma.AttributeValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttributeValue
   */
  omit?: Prisma.AttributeValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttributeValueInclude<ExtArgs> | null
  where?: Prisma.AttributeValueWhereInput
  orderBy?: Prisma.AttributeValueOrderByWithRelationInput | Prisma.AttributeValueOrderByWithRelationInput[]
  cursor?: Prisma.AttributeValueWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AttributeValueScalarFieldEnum | Prisma.AttributeValueScalarFieldEnum[]
}

/**
 * CV without action
 */
export type CVDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CV
   */
  select?: Prisma.CVSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CV
   */
  omit?: Prisma.CVOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CVInclude<ExtArgs> | null
}
